version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    restart: always
    # networks:
    #   - mynetwork
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
        - 27017:27017
    restart: always
    volumes:
      - ./data/db:/data/db
    # networks:
    # - mynetwork

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    # networks:
    #   - mynetwork

  nginx:
    build: ./nginx
    ports:
      - 22:80
    depends_on:
      - backend
      - frontend
    restart: always
#     networks:
#       - mynetwork

# networks:
#   mynetwork: