# version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    restart: always
    # volumes:
    #   - ./backend:

  mongodb:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app

  nginx:
    build: ./nginx
    ports:
      - 84:80
    depends_on:
      - backend
      - frontend
    restart: always