spring:
  application:
    name: backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/shortcut
#      host: localhost
#      port: 27017
#      authentication-database: admin
#      database: shortcut
#      username: qwe
#      password: 1234